# gitops-control-plane/Chart.yaml
apiVersion: v2
name: gitops-control-plane
description: The core App of Apps Bootstrap chart for Lost-Found-Project Platform
type: application
version: 1.0.0
appVersion: "1.0"