apiVersion: v2
name: backend
version: 1.0.0

# This is the magic! It tells Helm to download your OCI blueprint from AWS ECR
dependencies:
  - name: common-microservice  # This MUST match the 'name:' inside the blueprint's Chart.yaml
    version: 1.0.4            # This MUST match the 'version:' inside the blueprint's Chart.yaml
    repository: oci://815090125753.dkr.ecr.us-east-1.amazonaws.com/universal-helm-chart
